<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SimCoach.Audio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimCoach.Voice\SimCoach.Voice.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
  </ItemGroup>

</Project>
