<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SimCoach.Reference\SimCoach.Reference.csproj" />
    <ProjectReference Include="..\..\src\SimCoach.Storage\SimCoach.Storage.csproj" />
    <ProjectReference Include="..\..\src\SimCoach.Adapters.ACC\SimCoach.Adapters.ACC.csproj" />
  </ItemGroup>

</Project>
